Converted the class based style to function/hooks
DominicTobias/react-image-crop pull request #340
Opened 2020-03-09 20:39 UTC by RobKohr

2020-03-10 13:31 UTC, DominicTobias commented
Thanks I will merge this in but after I add back the commented stuff as I use that to test things ;) I'm working on something else at the moment so it will take some time before I get around to it

2021-01-02 19:17 UTC, martijndebruijn requested changes

2021-01-02 19:17 UTC, martijndebruijn commented on demo/demo.js
>  import ReactCrop from '../lib/ReactCrop';
I had to make to following changes to be able to compile the code.
import ReactCrop from 'react-image-crop';
import 'react-image-crop/dist/ReactCrop.css';

2021-01-02 19:17 UTC, martijndebruijn commented on demo/demo.js
>  ReactDOM.render(<App />, cropEditor);
CropEditor does not exist.
I used:
ReactDOM.render(<App />, document.getElementById("root"));

2021-01-07 15:04 UTC, DominicTobias commented
Thanks happy to merge but there seems to be a conflict there ^

2021-03-11 22:49 UTC, closed without merging